### ISSUE TITLE
Does this repo need a LICENSE or COPYING file?

### ISSUE THREAD

**Issue by edunham** [rust-lang/rfcs#1259]
re: https://github.com/rust-lang/rust/issues/25664

**Comment by jemc** [comment]
Any word on this?

I'm a part of another community that wants to adopt a similar RFC process to that used in the Rust community, but I noticed that the `rust-lang/rfcs` repo does not seem to have a license by which we could appropriately copy and attribute your work.

One additional wrinkle for this repo might be that the RFCs themselves might need a different license than that of the description of the process for contributing.  For example, you might want to use the same license as Rust for the RFCs themselves, while using a Creative Commons license of some kind for the description of the process.

---

As a nifty side-note, coincidentally, @edunham is one of the people who led me here, as I went to [her LFNW 2016 talk on "Rust's Community Automation"](https://www.linuxfestnorthwest.org/2016/sessions/rusts-community-automation) because I'm also trying to guide a growing language community for [Pony](http://www.ponylang.org/).

**Comment by ubsan** [comment]
This... should really be fixed. If we want to use any RFC text in any future standards, it seems bad not to have them as MIT/Whatever. Having people own a proprietary copyright on the rust specification (as that's how we have the RFCs, mostly)... :(

**Comment by SeanTAllen** [comment]
I'm part of the Pony core team. We're adopting a RFC process similar to Rust's. After talking to @steveklabnik and seeing that a couple other projects are using the materials heavily based on Rust's, I feel comfortable doing the same. If it turns out that was mistaken, please let me know. We'll be providing attribution back to the original Rust versions much in the same way that the Ember team has.

**Comment by est31** [comment]
Opened an RFC: https://github.com/rust-lang/rfcs/pull/2044
