### ISSUE TITLE
Array of objects with trait Clone should implement Clone

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rfcs#1334]
See https://play.rust-lang.org/?gist=c5ed4cbd5adfb89a8a0a&version=nightly

**Comment by main--** [comment]
Note that it works if the members are `Copy`. This [looks](https://github.com/rust-lang/rust/blob/master/src/libcore/array.rs#L98) like a deliberate design choice.

It makes sense: A struct is generally `Clone` but not `Copy` if cloning is a nontrivial operation (a convention your example doesn't adhere to). In the case of arrays, cloning is expensive because they're *big* - we don't want to `memcpy` huge arrays all over the place, so they're just `Clone`. As a result, it's a reasonable assumption that the cost of `clone()`ing an array is exactly that: Copying some memory. In case you *actually* want to go all the way and clone all of the array's *elements*, the typing overhead of `.iter().map(Clone::clone).collect::<Vec<_>>()` (or something similar) seems justified.

**Comment by wthrowe** [comment]
You can't `collect` into an array, though.  Also, `Vec` is already `Clone` if its members are, and it seems like the same arguments would apply there.

My guess is the `Copy` case was implemented because it is trivial but handling a `panic!` in one of the elements' `clone` calls would be tricky to do right.  (`Vec` handles this by incrementally resizing itself, but you can't resize an array.)

**Comment by withoutboats** [comment]
Impls for arrays are only present up to length 32 for all traits, and these are generated using a macro. I think the reason the impls don't exist is more mundane than either of the previous commenters guesses: an impl of `Clone` for non-`Copy` types requires an array literal of the form `[self[0].clone(), self[1].clone(), ...]`, which is not simple to construct for all lengths up to 32 using a single macro.

**Comment by wthrowe** [comment]
It's easy enough to write if you ignore panic safety (and the the discussion over on #197 about whether `mem::uninitialized` gives UB or not).  (untested)
```rust
impl<T: Clone> Clone for [T; $N] {
    fn clone(&self) -> Self {
        unsafe {
            let mut ret = mem::uninitialized();
            for i in 0..$N {
                ptr::write(&mut ret[i], self[i].clone());
            }
            ret
        }
    }
}
```
Might need a few tweaks to make the optimizer happy, of course.

The problem is that if a `clone` panics you drop a bunch of uninitialized `T`s.  A safe version would be something like:
```rust
impl<T: Clone> Clone for [T; $N] {
    fn clone(&self) -> Self {
        struct Cleanup<T> { arr: ManuallyDrop<[T; $N]>, initialized: uint }
        impl<T> Drop for Cleanup<T> {
            fn drop(&mut self) {
                for i in 0..self.initialized { drop(self.arr[i]); }
            }
        }
        unsafe {
            let mut ret = Cleanup { arr: mem::uninitialized(), initialized: 0 };
            for i in 0..$N {
                ptr::write(&mut ret[i], self[i].clone());

            }
            ret
        }
    }
}
```

**Comment by jonhoo** [comment]
Wait, @wthrowe, isn't the same issue present for tuples? And they implement `T` even if we just have `T: Clone` (i.e., not `T: Copy`)? Seems like either both of them should allow this, or neither?

**Comment by burdges** [comment]
@jonhoo Tuples exploit a [convenient macro system trick](https://doc.rust-lang.org/src/core/tuple.rs.html#25-29) but only exist up to length 12.  Arrays are [defined using a simpler macro](https://doc.rust-lang.org/src/core/array.rs.html#127-131) but they exist up to length 32.  You can write a macro to write out `[self[0].clone(), self[1].clone(), ...]` but doing so requires using a counter which I requires an extra layer of macro invocation.  

Ain't hard but these hacks should all get replaced by something akin to type level integers eventually, and tricks today risk boxing in the adoption path for improvements later.  In the recent past, there was no `ManuallyDrop`, so one could imagine that type level integers might allow relaxing `n <= 32` but only if `T: Copy`.  

I avoid the generic array crate myself, but [it handles Clone the way you want now](https://fizyk20.github.io/generic-array/generic_array/struct.GenericArray.html).

**Comment by wthrowe** [comment]
Another similar case is `#[derive(Clone)]` on structs.  I think that one is just built into the compiler.

**Comment by Centril** [comment]
> Arrays of any size are Copy if the element type is Copy and Clone if the element type is Clone. This works because Copy and Clone traits are specially known to the compiler.

https://doc.rust-lang.org/nightly/std/primitive.array.html

It appears this is implemented, so I'm closing the issue.
