### ISSUE TITLE
Add CStr::len()

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/rfcs#1441]
This seems like a natural addition. The implementation would use the inner slice for now, but eventually be equivalent to `strlen` whenever the `CStr` representation changes.

**Comment by kamalmarhubi** [comment]
I'm happy to do this, but am unclear on the process. Is an RFC required?

**Comment by nagisa** [comment]
Here’s the questions that could naturally arise:

* Should the length include trailing nul byte or should it not? Why? What are usecases for each one?
* If we went with any one of these, what about the other length? Do we expect `len() + 1` or `len() - 1` to be satisfactory answer?
* Are the gains justify adding this method if `cstr.as_bytes{,_with_nul}().len()` is essentially the same thing?

---

> eventually be equivalent to strlen whenever the CStr representation changes.

CStr and CString will not change the representation from keeping a slice and a `Vec` internally, because that representation is pretty much implied by the methods that return slices of bytes already.

**Comment by kamalmarhubi** [comment]
> Are the gains justify adding this method if `cstr.as_bytes{,_with_nul}().len()` is essentially the same thing?

No, they do not! Thanks for the alternative. :-)

> `CStr` will not change the representation from keeping a slice internally

The notes on various methods seem to suggest otherwise: 
https://doc.rust-lang.org/std/ffi/struct.CStr.html

as does the FIXME:
https://doc.rust-lang.org/stable/src/std/ffi/c_str.rs.html#140-146

**Comment by kamalmarhubi** [comment]
Closing as `to_bytes().len()` is more than fine.
