### ISSUE TITLE
Implement conversion traits for IpAddr

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rfcs#1816]
I'm thinking `From<Ipv4Addr>` and `From<Ipv6Addr>` at least.

**Comment by sfackler** [comment]
These seem pretty straightforward - feel free to open a PR adding them!

**Comment by seanmonstar** [comment]
I know I've often times wanted an easy way to create an `SocketAddr` without going through `FromStr`. There is a `new` constructor, but building an `IpAddr` is cumbersome. Maybe with `From<[u8; 4]>` or `From<(u8, u8, u8, u8)>`, or maybe as a `new` constructor on `IpAddr`.

I've wanted to reach for something like this, since it only requires the single `SocketAddr` import:

```rust
let addr = SocketAddr::new((127, 0, 0, 1), 8080);
```

But it would require changing `SocketAddr::new` to accept `<T: Into<IpAddr>>`...

**Comment by mattico** [comment]
A related (?) conversion which I think would be too confusing as a `From` impl would be converting IPv4 addresses to IPv6 mapped addresses (see https://tools.ietf.org/html/rfc4291 2.5.5.2). Perhaps `.to_v6()` or `.to_mapped()` or `.to_ipv6_mapped_addr()`? The shorter names may be confusing if you don't read the doc description, but so is most of the standard library.

**Comment by frewsxcv** [comment]
@mattico Interesting idea. It might be worth opening a separate issue for that so it can have its own separate discussion

**Comment by frewsxcv** [comment]
@mattico FYI, these methods already exist (I didn't know they existed until now):

* https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.to_ipv6_compatible
* https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.to_ipv6_mapped

**Comment by Yamakaky** [comment]
Cool!
