### ISSUE TITLE
add "#region" like C#

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rfcs#2062]
add "#region" like C#

**Comment by golddranks** [comment]
You should explain in the first post what #region does, since not all know C#.

If I recall correctly, it's just a directive for the IDE that allows defining a "logical" region of source code, which the editor can, for example, collapse. It doesn't affect the actual code semantics in any way.

It should be noted also, that Rust allows already attributes using syntax `#[attribute]`. Maybe using the already existing attribute syntax for IDE region hints could be feasible?

**Comment by eddyb** [comment]
You can just put it in comments as it done for C, C++, etc.

**Comment by wesleywiser** [comment]
As a C# developer, the only time I've seen `#region` used properly was to allow you to collapse the licensing text at the top of a source file. The other 99% of the times it has been to hide the fact that the file is way too long. If your file/class/function is big enough that you need to use regions, it's past time to break things up.

**Comment by jaroslaw-weber** [comment]
lot of c# programmers discourage use of region, you can do collapsing with ide or you can split the code in files

**Comment by sizeak** [comment]
I think this should be re-opened. There are uses for `#region` that aren't to "hide the fact that the file is way too long". Using `#region` for splitting up Public, Protected & Private members and methods helps to keep files tidy irrespective of whther they are long or short files.

**Comment by anonymoustafa** [comment]
> As a C# developer, the only time I've seen `#region` used properly was to allow you to collapse the licensing text at the top of a source file. The other 99% of the times it has been to hide the fact that the file is way too long. If your file/class/function is big enough that you need to use regions, it's past time to break things up.

Dear Wesley Wiser, 
1. Rust-lang is a functional language, we can't break things up without elongating our code!
1. Using an attribute like #region in Csharp helps to the legibility of the code.

**Comment by forteller11** [comment]
> As a C# developer, the only time I've seen `#region` used properly was to allow you to collapse the licensing text at the top of a source file. The other 99% of the times it has been to hide the fact that the file is way too long. If your file/class/function is big enough that you need to use regions, it's past time to break things up.

#I don't think the C#/Java OOP tendency to separate everything every little chunk of state+function into it's own file is necessarily a good habit. Especially for a systems programming language long files can be expected. Systems do not get less complex just because their complexity is amortized over the filesystem. #region #endregion are a way to program in this systems programming style while still offerings progs softer methods to group and compartmentalize features _within_ a single file.

**Comment by truppelito** [comment]
Personally I'm a big fan of the way Swift handles this. Swift uses comments with specific keywords such as: `// MARK: xxx`, `// MARK: -`, `// TODO: xxx`, `// FIXME: xxx`, etc. In my opinion, this is in line with Rust, as we already have the `/// xxx` format for documentation. Also, it would not require any changes to the language itself: this is just an addition to the common practice of the language. Finally, it would be easily picked up by any IDE ([example](https://stackoverflow.com/a/35963262/778396) of how this works for Swift in Xcode).

**Comment by eddyb** [comment]
> Swift uses comments with specific keywords such as: `// MARK: xxx`, `// MARK: -`, `// TODO: xxx`, `// FIXME: xxx`, etc.

I've seen (and used) the `TODO`/`FIXME` ones (or, my favorite, *`HACK`*) in most languages I've used.

`// FIXME: ...` (and the "attributed" variant, e.g.: `// FIXME(eddyb) ...`) comments are widely used in the Rust compiler itself, and have been for the past decade.

And some IDEs will highlight some of those comments across multiple languages.

<hr/>

However, I haven't seen anything *that* common for collapsible regions.

But a quick search for VSCode reveals https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder which after some quick testing does seem to work with `/* #region ... */` `/* #endregion */` comments in Rust (sadly it doesn't support `//` comments for Rust but it does for C, so it can likely be fixed to treat Rust like C, or the instructions in its documentation can be used to locally add support).

<hr/>

So IMO, there are two *separate* issues here:
* standardizing on the shape of such comments (if we want to have an "official style" for it)
  * there's the C# inspired form (`// #region`)
  * KDE editors (`kwrite`/`kate`/`kdevelop`, which I used before VSCode) [appear to support `//BEGIN` and `//END`](https://github.com/KDE/syntax-highlighting/blob/778fa485c8e9027cf78f363f0c19e7db0c89c515/data/syntax/c.xml#L154-L155)
  * using `{` in the start comment and `}` in the end comment (instead of the `end` word) feels like something I *may* have seen, but I have no idea where (maybe doc comments in a language other than Rust? maybe it involved `@{`? not sure)
* IDE support for non-trivial treatment of comments (whether `// FIXME` or folding)
  * should the VSCode RA extension offer such functionality?
  * that "region folder" extension could be likely be updated with different Rust defaults

OTOH, I would not expect non-comment alternatives to be a viable proposal (that is, one could try to open an RFC for them, but I doubt it would receive a lot of support).

My best guess as to how this could move forward, would be someone posting to the [internals](https://internals.rust-lang.org/) and/or [users](https://users.rust-lang.org/) forums to gather some opinions on what people might want to use (i.e. subjective aesthetics).

If this *does* lead to some kind of agreement, there are a few places where I've seen/added a non-doc comment (with empty lines before and after it), to indicate the start of a new "section", that could use it.

**Comment by lemonJumps** [comment]
To add my two cents to this. as someone who commonly works with c++ and python.

region folding is not a feature of the language (except for C#, kind of), but of the IDEs.
C++ uses `#pragma region <name>` and `#pragma endregion` which is in the terms of the language, nonsense that is ignored by the compiler.
Python uses `#region <name>` and `#endregion`, which is a comment.
JAVA (in the jetbrains IDE, and maybe others) uses `//region <name>` and `//endregion`.
It's always something non-destructive that is just tacked on, and ignored by the language it self.

So, honestly, I think the best way to get region folding for rust, is to just write a plugin for your favourite IDE, publish it and see If others like it too :D
