### ISSUE TITLE
Support setter syntax

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rfcs#2248]
Support setter syntax or let `pub` in `struct` get only
https://github.com/rust-lang/rfcs/issues/2247

**Comment by 3442853561** [comment]
The setter syntax can make programmers lazy and reduce errors.
There are two implementation suggestions: a Setter trait or let `pub` in `struct` get only like #2247

**Comment by Centril** [comment]
How would such a `Setter` trait look like?
And why is this in particular a problem that needs special language support rather than just writing out inherent methods yourself?

**Comment by 3442853561** [comment]
Because some popular languages have this syntax. It can make Rust more easily and friendly. It also a practical syntax.

**Comment by 3442853561** [comment]
@Centril I think let `pub` in `struct` get only like #2247 is better

**Comment by Centril** [comment]
Some related reading and work:
+ https://mail.mozilla.org/pipermail/rust-dev/2012-July/002154.html
+ https://www.reddit.com/r/rust/comments/2uvfic/why_doesnt_rust_have_properties/
+ https://github.com/emk/accessors
+ https://github.com/Hoverbear/getset

We can't change the meaning of `pub` in `struct` because that would break people's code on stable. We have to maintain backwards-compatibility.

If we do something like this (and I'm not saying we should since I don't see a great need for it), I counter-propose that a user be able to write:

```rust
#[derive(Debug)]
pub struct Bar(u8);

#[derive(Debug)]
pub struct Foo {
    my_field: Bar
}

impl Foo {
    pub fn new(bar: Bar) -> Self {
        Self { my_field: bar }
    }

    #[getter(bar)]
    pub fn randomly_named(&self) -> &Bar { &self.my_field }

    #[setter(bar)]
    pub fn other_name(&mut self, bar: Bar) { self.my_field = Bar(bar.0 + 1); }

    // This also works instead:

    #[setter(bar)]
    pub fn other_name(&mut self) -> &mut Bar { &mut self.my_field }
}

// somewhere else:
fn main() {
    // Today:
    let bar = Bar(0);
    let mut foo = Foo::new(bar);
    foo.randomly_named(Bar(1));
    // or:
    *foo.randomly_named() = Bar(1);
    println!("{:?}", foo.randomly_named());
    
    // Future:
    foo.bar = Bar(1);
    println!("{:?}", foo.bar);
}
```

**Comment by 3442853561** [comment]
I guess it is better to write a crate, however not the standard library. Thank you
