### ISSUE TITLE
reverse iterator

### ISSUE THREAD

**Issue by mehrati** [rust-lang/rfcs#2269]
i don't love this code 
`for i in (1..10).rev(){
         println!("{}",i);
}`
why we can't use this cleaner code in rust-lang
`for i in 10..1{
         println!("{}",i);
}`

**Comment by Centril** [comment]
If we think about this mathematically..

The range `10..1` can be seen as the set formed by: `{ x | is_integer(x) && 10 <= x < 1 }`.
This holds for exactly zero integers, wherefore the set is empty.

It is important to not have surprising and different semantics than to mathematics.
I think that the hassle of `.rev()` is not too large and well worth this consistency.

**Comment by scottmcm** [comment]
@mehrati Because it would be surprising in cases that aren't literals.

For example, today the following code is fine:
```rust
for i in 5..v.len() { println!("{}", v[i]); }
```
If the container is smaller than 5 elements, the loop doesn't run.  If it started iterating the other way instead, it would result in panicking with out-of-range would be both confusing and a breaking change.

**Comment by Centril** [comment]
Triaging this issue:

@mehrati: is the given explanation sufficient for you? can we close this?

**Comment by mehrati** [comment]
yes very thank you fellow-citizen.
no problem you can close this

**Comment by Centril** [comment]
Thanks =)
