### ISSUE TITLE
Find something interesting, might be a bug

### ISSUE THREAD

**Issue by LittleLittleCloud** [rust-lang/rfcs#2332]
Hi, I'm a beginner in rust, and I'm not quite sure that the problem is my mistake or it is a rust's trait. 

To be short, the problem is as followed: one can still get the mutable reference of an immutable in-class member through `ref mut ...` without any `unsafe` mark

My rustc version is as followed:
`rustc 1.25.0-nightly (b5392f545 2018-01-08) `

the code is as followed:
```
use std::io::Write;
#[derive(Debug)]
struct A {
    i:i32
}
#[derive(Debug)]
struct B {
    inner: Option<A>
}
impl B {
    // add code here
    fn inner(&mut self)-> &mut A{
        match self.inner {
            Some(ref mut a) => a,
            None => panic!("..."),
        }
    }
}
fn main(){
    let mut b=&mut B{
        inner:Some(A{
            i:0
        })
    };
    //this can't pass compiler
    //error[E0507]: cannot move out of borrowed content
    // let mut a_fail=&mut b.inner.unwrap();

    //this can pass, however
    let mut a_pass=b.inner();
    *a_pass=A{
        i:1
    };
    //res: A { i: 1 }
    print!("{:?}",a_pass);
}
```

Thanks for your reading, any reply would be helpful.

**Comment by eddyb** [comment]
Bug reports should go to rust-lang/rust, not the RFC repo.
Nothing is immutable here, you have "mut" on literally every place that allows the keyword.
`&mut b.inner.unwrap()` doesn't do what you'd expect (it tries to steal the value and then borrow it, instead of borrowing the original location), `b.inner.as_mut().unwrap()` is what you're looking for.
