### ISSUE TITLE
Make rust crate name support "-" not replace with "_"

### ISSUE THREAD

**Issue by Allenyn** [rust-lang/rfcs#2650]
Make rust crate name support "-" not replace with "_"

**Comment by Allenyn** [comment]
by **jjc.jclark.com**:

The spec defines identifier like this:

  identifier = letter { letter | unicode_digit }

where letter is _ or class Lu, Ll, Lt, Lm, or Lo.

This doesn't work for languages with combining characters (e.g. South and
South-East Asian languages).  For example, in Thai some vowels have
combining class Lo and some vowels have combining class Mn.

There's lots of details in

http://www.unicode.org/reports/tr31/

I would actually recommend using

http://www.unicode.org/reports/tr31/#Alternative_Identifier_Syntax

This keeps things simple and ensures that the definition of an identifier
is Unicode version independent.

**Comment by Ixrec** [comment]
What spec are you referring to? (I can't find any formal definition of legal crate names in the cargo book)

I believe the current hyphen and underscores behavior comes from https://github.com/rust-lang/rfcs/pull/940. It seems clear that we would've gone with a less weird system had we considered this issue from day one, but the argument that forcing several thousand hyphenated crate names to change is just not worth it seems pretty strong to me. Has anything significant changed since then?

**Comment by Allenyn** [comment]
@Ixrec I just want one more choice. There is no need to change other crate names.

**Comment by Allenyn** [comment]
@Ixrec I am done. You can close it. I know it won't be solved.
