### ISSUE TITLE
Loop x times

### ISSUE THREAD

**Issue by pbbob** [rust-lang/rfcs#2792]
It would be nice to be able to do this:
```Rust
let count = 15;
loop count {
    println!("{}", count);
}
```
would loop 15 times.

**Comment by KrishnaSannasi** [comment]
Whats wrong with

```rust
for _ in 0..15 {
    println!("{}", count);
}

```

**Comment by pbbob** [comment]
@KrishnaSannasi 
> Whats wrong with
> 
> ```rust
> for _ in 0..15 {
>     println!("{}", count);
> }
> ```

These have different semantic meanings. `for _ in 0..15` is the same as `for _ in 1234..1249`. `loop 15` makes it clear that it is just being repeated x times.

**Comment by KrishnaSannasi** [comment]
Ok, how often do you actually need to repeat a thing a fixed number of times? I don't see the point of this extensions, especially when `for _ in 0..count { ... }` does the job and is very clear. Keeping `0` as the lower bound and using `_` to ignore the iterator items makes it clear that you want to do a thing a fixed number of times.

Extending `loop` to do this doesn't seem to be very productive, or add very much. In fact I find it detracts from the meaning of `loop` a bit. I find utility in knowing that when I see `loop`, there is something strange going on with the control flow. So, adding `loop $count { ... }`, while minor on it's own, does somewhat break this rule. (Although, I have seen other proposals to do exactly this, so there may be some merit to adding it)

Finally, there is the concern of how to handle `break` in this `loop`.

Right now, you can do this.

```rust
assert_eq!(1, loop { break 1 });
```

I would expect `loop $count { break 1 }` to be a compiler error, because the loop could end gracefully similarly to how `for _ in 0..$count { break 1 }` is an error.

**Comment by phaazon** [comment]
`for _ in 0 .. nb` is pretty clear to me and already small enough. Furthermore, loop constructs have contracts:

- `for` is often used for deterministic looping — i.e. when you know at most how many times you’ll iterate.
- `while` is used to loop while a condition is held true, which is already different from the previous construct.
- `loop` is used to loop without even knowing the condition and requires a break.

What you describe falls in the first family of constructs and I suggest you simply add macro for it or just an `Iterator` type, such as:

```rust
for _ in times(3) {
}
```

Or,

```rust
times(3, || {
});
```

**Comment by Centril** [comment]
It seems unlikely that we would support this given that we also closed https://github.com/rust-lang/rfcs/pull/2617. There also doesn't seem to be any strong support or motivation. Closing therefore.
