### ISSUE TITLE
Friend keyword

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rfcs#2839]
I think, it's need introduce "friend" keyword in rust, as it used in C++, for advanced access restrictions

**Comment by burdges** [comment]
Already exists as `pub(...)` https://github.com/rust-lang/rfcs/blob/master/text/1422-pub-restricted.md

**Comment by Lokathor** [comment]
What does any of that mean?

**Comment by ExpHP** [comment]
We have

```rust
pub(crate) fn foo {} // visible to whole crate
pub(super) fn foo {} // visible to parent module
pub(in crate::foo) fn foo {} // visible to ancestor module
```

Strictly speaking, we don't have a way to specify visibility to another, non-ancestor module.  But I've never missed this functionality.

C++ needs `friend` because its privacy model is centered around classes.  Private fields can normally only be seen by member functions (methods), which is an issue when a non-member function such as `operator==(const std::string&, const mytype&)` requires access to functionality of your type that you may not want to expose to the general public.

Because Rust's privacy model is centered around modules, it does not have this issue.

**Comment by aristarh2704** [comment]
It's possible specify visibility for non-ancestor modules?

**Comment by KrishnaSannasi** [comment]
@aristarh2704 no it is not, but why would you want to?

**Comment by Centril** [comment]
My feeling here is that what we've got is already enough and as far as I know, the language team is probably more inclined to not add more visibility modes like this -- rather, to my knowledge there is some support to reduce the variety.
