### ISSUE TITLE
add .eval function

### ISSUE THREAD

**Issue by Ap0ph1s** [rust-lang/rfcs#801]
Similar to what Ruby has, we should add a .eval() to eval function to Rust so we build REPL like applications.

**Comment by steveklabnik** [comment]
We already have the start of a REPL without `eval`: https://github.com/murarth/rusti

**Comment by Ap0ph1s** [comment]
How can we use this inside actual code?

**Comment by netvl** [comment]
@Ap0ph1s, note that Rust is a compiled language, while Ruby and other scripting languages are interpreted. Naturally, it is much easier to implement `eval()` function in interpreted languages. In order to implement `eval()` in Rust you will need, in particular, bring `librustc` and all dependent crates along with your program. It is not impossible (at least I think so) but it is hard to implement correctly and conveniently. And making convenient REPL (with history, variable bindings, etc.) is even harder.

**Comment by sinistersnare** [comment]
-1, look at any article when googling "eval is evil"

I suggest looking into hooking up librustc/libsyntax, but I do not want a function as simple as eval in the Rust stdlib.
