### ISSUE TITLE
Rustdoc should support top-level code blocks that apply to all subsequent examples

### ISSUE THREAD

**Issue by felixc** [rust-lang/rfcs#919]
It would be great if it were possible to define a block of code at the top of a file/module, and have its effects apply throughout the rest of the rustdoc code snippets/examples. Think of it as the "#" feature that hides some code, but made even better.

This would be useful when individual function/method examples are small and simple, but they all require a large amount of identical setup code. It would be possible to write that setup code just once, at the top of the file, and then have each example snippet only show what's actually relevant. This is an improvement over copying and pasting bulky hidden boilerplate over and over again for every example.

Another, perhaps controversial, use case would be to put "`use mymodule::*;`" at the top of file, so that all the examples in `mymodule` could use unprefixed names.

It might even make sense to have each example link back to the implicitly-included blocks, or have a toggle to show them.

**Comment by FraGag** [comment]
It's possible to write a macro to avoid repeating the setup code. Here's an example (this is a "[TT muncher][tt-munchers]" macro):

```
macro_rules! def {
    (@ (#[$attr:meta] $($rest:tt)*) -> ($($result:tt)*)) => {
        def! { @ ($($rest)*) -> ($($result)* #[$attr]) }
    };
    (@ (example { $(#[$attrs:meta])* } $($rest:tt)*) -> ($($result:tt)*)) => {
        def! { @ ($($rest)*) -> (
            $($result)*
            ///
            /// ```
            /// # extern crate rand;
            /// # fn main() {
            $(#[$attrs])*
            /// # }
            /// ```
            ///
        ) }
    };
    (@ ($item:item) -> ($($result:tt)*)) => {
        $($result)* $item
    };
    ($($tt:tt)*) => {
        def! { @ ($($tt)*) -> () }
    };
}

def! {
    /// Does nothing.
    example {
        /// use rand::Rng;
        ///
        /// let mut rng = rand::thread_rng();
        /// if rng.gen() { // random bool
        ///     println!("i32: {}, u32: {}", rng.gen::<i32>(), rng.gen::<u32>())
        /// }
    }
    pub fn foo() {
        // Do nothing.
    }
}
```

It relies on the fact that documentation comments are syntactic sugar for `#[doc = "..."]` attributes. The macro must take the item the doc comments are attached to as input, because a macro cannot expand only to attributes. However, the `item` matcher matches any kind of [item][items], so it's pretty general.

[tt-munchers]: https://danielkeep.github.io/tlborm/book/pat-incremental-tt-munchers.html
[items]: https://doc.rust-lang.org/reference/items.html
